### ISSUE TITLE
In chrome SwipeView interferes with jquery mobile

### ISSUE THREAD

**Issue by karussell** [cubiq/SwipeView#5]
I know this is a mobile lib, but it works good on chrome (but not at alll in firefox 8?)

When adding the jquery mobile lib after or before including SwipeView then the SwipeView does not properly animate (only tested with the inline demo) It says:

Uncaught TypeError: Cannot read property 'style' of undefined (line 349, SwipeView.__checkPosition)

(BTW On Android SwipeView works with jquery mobile)

this can be prevented via $(window).load(function() { /\* swipview init code */ }) or what do you suggest?

**Comment by jurgenbrouwer** [comment]
Hi, I think I had the same problem as you describe here.
The problem occurs because this.wrapper.clientWidth in the function refreshSize is not available when JQuery Mobile is loaded and defaults to zero. I guess it has something to do with the viewport it is in.

A work around for me was to get the clientWidth for the body (since my carousel has the same width).

So in refreshSize I set:

this.wrapperWidth = document.getElementById('body').clientWidth; //jquery mobile hack

I hope this helps.

**Comment by complexite** [comment]
Has there been any updates related to this issue?? I've tried the solution above but it doesn't seem to solve the issue. 

Does anyone have additional solutions/suggestions on how to solve this?
